# SPDX-FileCopyrightText: 2022 Serokell <https://serokell.io>
#
# SPDX-License-Identifier: MPL-2.0

main_backend = "pass"

[[backend]]
type = "debug"
sub_type = "pass"
name = "pass"
store_dir = "/tmp/pass-store"
pass_exe = "pass"