# SPDX-FileCopyrightText: 2022 Serokell <https://serokell.io>
#
# SPDX-License-Identifier: MPL-2.0

steps:
  - label: check trailing whitespaces
    command: nix-build ci.nix -A trailing-whitespace-check

  - label: shellcheck
    command: nix run -f ci.nix pkgs.shellcheck -c find . -name '*.sh' -exec shellcheck {} +

  - label: validate cabal files
    command: nix run -f ci.nix stack2cabal -c ./scripts/validate-cabal-files.sh

  - label: stylish
    command: nix run -f ci.nix pkgs.gnumake pkgs-stylish.stylish-haskell -c ./scripts/validate-stylish.sh

  - label: build
    key: build
    command: nix-build ci.nix -A lib -A cli

  - label: tests
    depends_on: build
    commands:
      - nix-build ci.nix -A tests
      - ./result/bin/test

  - label: golden tests
    depends_on: build
    commands:
      - export PATH=$(nix-build ci.nix -A project.coffer.components.exes.coffer --no-out-link)/bin:$PATH
      - nix run
          -f ci.nix pkgs.vault pkgs.bats
          -c ./scripts/run-bats-tests.sh

  - label: haddock
    depends_on: build
    command: nix-build ci.nix -A haddock

  - label: linux static executable
    command: nix-build ci.nix -A coffer-static
    artifact_paths:
      - "result/bin/coffer"

  - label: xrefcheck
    command: nix run -f ci.nix xrefcheck -c xrefcheck --no-progress -m full --ignored tests/golden/helpers

  - label: REUSE lint
    command: nix run -f ci.nix pkgs.reuse -c reuse lint

  - label: weeder
    depends_on: build
    commands:
      - nix-build ci.nix -A weeder-script
      - ./result
