# SPDX-FileCopyrightText: 2022 Serokell <https://serokell.io>
#
# SPDX-License-Identifier: MPL-2.0

steps:
  - label: check trailing whitespaces
    command: nix-build ci.nix -A trailing-whitespace-check

  - label: shellcheck
    command: nix shell -f ci.nix pkgs.shellcheck -c find . -name '*.sh' -exec shellcheck {} +

  - label: validate cabal files
    command: nix shell -f ci.nix stack2cabal pkgs.diffutils -c ./scripts/validate-cabal-files.sh

  - label: stylish
    command: nix shell -f ci.nix pkgs.gnumake pkgs-stylish.stylish-haskell -c ./scripts/validate-stylish.sh

  - label: lint
    command: nix shell -f ci.nix pkgs.haskellPackages.hlint -c hlint .

  - label: build
    key: build
    command: nix-build ci.nix -A lib -A cli -A server

  - label: swagger docs
    depends_on: build
    commands:
      - nix-build ci.nix -A coffer-swagger-api
      - ./scripts/validate-swagger-docs.sh ./result/bin/coffer-swagger-api

  - label: server integration
    depends_on: build
    commands:
      - nix-build ci.nix -A server-integration
      - ./result/bin/server-integration

  - label: tests
    depends_on: build
    commands:
      - nix-build ci.nix -A tests
      - ./result/bin/test

  - label: golden tests
    depends_on: build
    commands:
      - export PATH=$(nix-build ci.nix -A project.coffer.components.exes.coffer --no-out-link)/bin:$PATH
      - nix shell
          -f ci.nix pkgs.vault pkgs.bats
          -c ./scripts/run-bats-tests.sh

  - label: haddock
    depends_on: build
    command: nix-build ci.nix -A haddock

  - label: linux static executable
    command: nix-build ci.nix -A coffer-static
    artifact_paths:
      - "result/bin/coffer"

  - label: xrefcheck
    command: nix shell -f ci.nix xrefcheck -c xrefcheck

  - label: REUSE lint
    command: nix shell -f ci.nix pkgs.reuse -c reuse lint

  - label: weeder
    depends_on: build
    commands:
      - nix-build ci.nix -A weeder-script
      - ./result
